// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	IndexString_Size_0 int = base.AtoiNoErr(Atoi("0"))
	IndexString_Size   int = IndexString_Size_0
)

// (field inedx, field type) -> IndexString_IdxToType
var DUMMY_IndexString_Size bool = SetIndexStringFields("IndexString", "Size", "Int32", IndexString_Size_0)

func (node IndexString) Size() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(IndexString_Size_0)

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node IndexString) SetSize(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v)
}
