// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	IndexNum_Maps_1 int = base.AtoiNoErr(Atoi("1"))
	IndexNum_Maps   int = IndexNum_Maps_1
)

// (field inedx, field type) -> IndexNum_IdxToType
var DUMMY_IndexNum_Maps bool = SetIndexNumFields("IndexNum", "Maps", "[]InvertedMapNum", IndexNum_Maps_1)

func (node IndexNum) Maps() (result *InvertedMapNumList) {
	result = emptyInvertedMapNumList()
	common := node.FieldAt(IndexNum_Maps_1)

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node IndexNum) SetMaps(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(1, v)
}
