// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type KeyRecordList struct { // genny
	*CommonNode
}

// KeyRecord genny
func NewKeyRecordList() *KeyRecordList {

	list := emptyKeyRecordList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]KeyRecord"

	list.InitList()
	return list
}

func emptyKeyRecordList() *KeyRecordList {
	return &KeyRecordList{CommonNode: &base.CommonNode{}}
}

func (node KeyRecordList) At(i int) (result *KeyRecord, e error) {
	result = &KeyRecord{}
	result.CommonNode, e = node.CommonNode.At(i)
	return
}

func (node KeyRecordList) SetAt(i int, v *KeyRecord) error {
	return node.CommonNode.SetAt(i, v.CommonNode)
}

func (node KeyRecordList) First() (result *KeyRecord, e error) {
	return node.At(0)
}

func (node KeyRecordList) Last() (result *KeyRecord, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node KeyRecordList) Select(fn func(*KeyRecord) bool) (result []*KeyRecord) {
	result = make([]*KeyRecord, 0, int(node.NodeList.ValueInfo.VLen))
	commons := node.CommonNode.Select(func(cm *CommonNode) bool {
		return fn(&KeyRecord{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &KeyRecord{CommonNode: cm})
	}
	return result
}

func (node KeyRecordList) Find(fn func(*KeyRecord) bool) *KeyRecord {
	result := &KeyRecord{}
	result.CommonNode = node.CommonNode.Find(func(cm *CommonNode) bool {
		return fn(&KeyRecord{CommonNode: cm})
	})
	return result
}

func (node KeyRecordList) All() []*KeyRecord {
	return node.Select(func(*KeyRecord) bool { return true })
}

func (node KeyRecordList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}
