// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type RecordList struct { // genny
	*CommonNode
}

// Record genny
func NewRecordList() *RecordList {

	list := emptyRecordList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]Record"

	list.InitList()
	return list
}

func emptyRecordList() *RecordList {
	return &RecordList{CommonNode: &base.CommonNode{}}
}

func (node RecordList) At(i int) (result *Record, e error) {
	result = &Record{}
	result.CommonNode, e = node.CommonNode.At(i)
	return
}

func (node RecordList) SetAt(i int, v *Record) error {
	return node.CommonNode.SetAt(i, v.CommonNode)
}

func (node RecordList) First() (result *Record, e error) {
	return node.At(0)
}

func (node RecordList) Last() (result *Record, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node RecordList) Select(fn func(*Record) bool) (result []*Record) {
	result = make([]*Record, 0, int(node.NodeList.ValueInfo.VLen))
	commons := node.CommonNode.Select(func(cm *CommonNode) bool {
		return fn(&Record{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &Record{CommonNode: cm})
	}
	return result
}

func (node RecordList) Find(fn func(*Record) bool) *Record {
	result := &Record{}
	result.CommonNode = node.CommonNode.Find(func(cm *CommonNode) bool {
		return fn(&Record{CommonNode: cm})
	})
	return result
}

func (node RecordList) All() []*Record {
	return node.Select(func(*Record) bool { return true })
}

func (node RecordList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}
