// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Root_Version_0 int = base.AtoiNoErr(Atoi("0"))
	Root_Version   int = Root_Version_0
)

// (field inedx, field type) -> Root_IdxToType
var DUMMY_Root_Version bool = SetRootFields("Root", "Version", "Int32", Root_Version_0)

func (node Root) Version() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(Root_Version_0)
	if common.Node == nil {
		result = NewCommonNode()
		node.SetFieldAt(Root_Version_0, result.SelfAsCommonNode())
		common = node.FieldAt(Root_Version_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node Root) SetVersion(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v)
}
