// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type RootList struct { // genny
	*CommonNode
}

// Root genny
func NewRootList() *RootList {

	list := emptyRootList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]Root"

	list.InitList()
	return list
}

func emptyRootList() *RootList {
	return &RootList{CommonNode: &base.CommonNode{}}
}

func (node RootList) At(i int) (result *Root, e error) {
	result = &Root{}
	result.CommonNode, e = node.CommonNode.At(i)
	return
}

func (node RootList) First() (result *Root, e error) {
	return node.At(0)
}

func (node RootList) Last() (result *Root, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node RootList) Select(fn func(*Root) bool) (result []*Root) {
	result = make([]*Root, 0, int(node.NodeList.ValueInfo.VLen))
	commons := node.CommonNode.Select(func(cm *CommonNode) bool {
		return fn(&Root{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &Root{CommonNode: cm})
	}
	return result
}

func (node RootList) Find(fn func(*Root) bool) *Root {
	result := &Root{}
	result.CommonNode = node.CommonNode.Find(func(cm *CommonNode) bool {
		return fn(&Root{CommonNode: cm})
	})
	return result
}

func (node RootList) All() []*Root {
	return node.Select(func(*Root) bool { return true })
}

func (node RootList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}
