// Code generated by "stringer -type=SkipType"; DO NOT EDIT.

package vfsindex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SkipFalse-0]
	_ = x[SkipTrue-1]
	_ = x[SkipFinish-2]
}

const _SkipType_name = "SkipFalseSkipTrueSkipFinish"

var _SkipType_index = [...]uint8{0, 9, 17, 27}

func (i SkipType) String() string {
	if i >= SkipType(len(_SkipType_index)-1) {
		return "SkipType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SkipType_name[_SkipType_index[i]:_SkipType_index[i+1]]
}
