// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package vfs_schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PathInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsPathInfo(buf []byte, offset flatbuffers.UOffsetT) *PathInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PathInfo{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PathInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PathInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PathInfo) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PathInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PathInfoAddPath(builder *flatbuffers.Builder, path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(path), 0)
}
func PathInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
