// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package vfs_schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Symbols struct {
	_tab flatbuffers.Table
}

func GetRootAsSymbols(buf []byte, offset flatbuffers.UOffsetT) *Symbols {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Symbols{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Symbols) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Symbols) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Symbols) Symbols(obj *Symbol, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Symbols) SymbolsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SymbolsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SymbolsAddSymbols(builder *flatbuffers.Builder, symbols flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(symbols), 0)
}
func SymbolsStartSymbolsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SymbolsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
