// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type FilesList struct { // genny
	*CommonNode
}

// Files genny
func NewFilesList() *FilesList {

	list := emptyFilesList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]Files"

	(*base.List)(list.CommonNode).InitList()
	return list
}

func emptyFilesList() *FilesList {
	return &FilesList{CommonNode: &base.CommonNode{}}
}

func (node FilesList) At(i int) (result *Files, e error) {
	result = &Files{}
	result.CommonNode, e = (*base.List)(node.CommonNode).At(i)
	return
}

func (node FilesList) AtWihoutError(i int) (result *Files) {
	result, e := node.At(i)
	if e != nil {
		result = nil
	}
	return
}

func (node FilesList) SetAt(i int, v *Files) error {
	return (*base.List)(node.CommonNode).SetAt(i, v.CommonNode)
}
func (node FilesList) Add(v FilesList) error {
	return (*base.List)(node.CommonNode).Add((*base.List)(v.CommonNode))
}

func (node FilesList) Range(start, last int) *FilesList {
	l := (*base.List)(node.CommonNode).New(base.OptRange(start, last))
	if l == nil {
		return nil
	}
	return &FilesList{CommonNode: (*base.CommonNode)(l)}
}

func (node FilesList) First() (result *Files, e error) {
	return node.At(0)
}

func (node FilesList) Last() (result *Files, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node FilesList) Select(fn func(*Files) bool) (result []*Files) {
	result = make([]*Files, 0, int(node.NodeList.ValueInfo.VLen))
	commons := (*base.List)(node.CommonNode).Select(func(cm *CommonNode) bool {
		return fn(&Files{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &Files{CommonNode: cm})
	}
	return result
}

func (node FilesList) Find(fn func(*Files) bool) *Files {
	result := &Files{}
	result.CommonNode = (*base.List)(node.CommonNode).Find(func(cm *CommonNode) bool {
		return fn(&Files{CommonNode: cm})
	})
	return result
}

func (node FilesList) All() []*Files {
	return node.Select(func(*Files) bool { return true })
}

func (node FilesList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}

func (node FilesList) SwapAt(i, j int) error {
	return (*List)(node.CommonNode).SwapAt(i, j)
}

func (node FilesList) SortBy(less func(i, j int) bool) error {
	return (*List)(node.CommonNode).SortBy(less)
}

// Search ... binary search
func (node FilesList) Search(fn func(*Files) bool) *Files {
	result := &Files{}

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&Files{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		result, _ = node.At(i)
	}

	return result
}

func (node FilesList) SearchIndex(fn func(*Files) bool) int {

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&Files{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		return i
	}

	return -1
}
