// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type FilesList struct { // genny
	*CommonNode
}

// Files genny
func NewFilesList() *FilesList {

	list := emptyFilesList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]Files"

	list.InitList()
	return list
}

func emptyFilesList() *FilesList {
	return &FilesList{CommonNode: &base.CommonNode{}}
}

func (node FilesList) At(i int) (result *Files, e error) {
	result = &Files{}
	result.CommonNode, e = node.CommonNode.At(i)
	return
}

func (node FilesList) SetAt(i int, v *Files) error {
	return node.CommonNode.SetAt(i, v.CommonNode)
}

func (node FilesList) First() (result *Files, e error) {
	return node.At(0)
}

func (node FilesList) Last() (result *Files, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node FilesList) Select(fn func(*Files) bool) (result []*Files) {
	result = make([]*Files, 0, int(node.NodeList.ValueInfo.VLen))
	commons := node.CommonNode.Select(func(cm *CommonNode) bool {
		return fn(&Files{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &Files{CommonNode: cm})
	}
	return result
}

func (node FilesList) Find(fn func(*Files) bool) *Files {
	result := &Files{}
	result.CommonNode = node.CommonNode.Find(func(cm *CommonNode) bool {
		return fn(&Files{CommonNode: cm})
	})
	return result
}

func (node FilesList) All() []*Files {
	return node.Select(func(*Files) bool { return true })
}

func (node FilesList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}
