// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Files_Files_0 int = base.AtoiNoErr(Atoi("0"))
	Files_Files   int = Files_Files_0
)

// (field inedx, field type) -> Files_IdxToType
var DUMMY_Files_Files bool = SetFilesFields("Files", "Files", "[]File", Files_Files_0)

func (node Files) Files() (result *FileList) {
	result = emptyFileList()
	common := node.FieldAt(Files_Files_0)
	if common.Node == nil {
		result = NewFileList()
		node.SetFieldAt(Files_Files_0, result.SelfAsCommonNode())
		common = node.FieldAt(Files_Files_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node Files) SetFiles(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v)
}
