// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	IdxEntry_Pathinfos_0 int = base.AtoiNoErr(Atoi("0"))
	IdxEntry_Pathinfos   int = IdxEntry_Pathinfos_0
)

// (field inedx, field type) -> IdxEntry_IdxToType
var DUMMY_IdxEntry_Pathinfos bool = SetIdxEntryFields("IdxEntry", "Pathinfos", "[]PathInfo", IdxEntry_Pathinfos_0)

func (node IdxEntry) Pathinfos() (result *PathInfoList) {
	result = emptyPathInfoList()
	common := node.FieldAt(IdxEntry_Pathinfos_0)
	if common.Node == nil {
		result = NewPathInfoList()
		node.SetFieldAt(IdxEntry_Pathinfos_0, result.SelfAsCommonNode())
		common = node.FieldAt(IdxEntry_Pathinfos_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node IdxEntry) SetPathinfos(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v)
}
