// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"github.com/kazu/fbshelper/query/base"
	"github.com/kazu/fbshelper/query/log"
)

/*
must call 1 times per Table / struct ( IdxEntry ) ;
*/

type IdxEntry struct {
	*base.CommonNode
}

func emptyIdxEntry() *IdxEntry {
	return &IdxEntry{CommonNode: &base.CommonNode{}}
}

var IdxEntry_IdxToType map[int]int = map[int]int{}
var IdxEntry_IdxToTypeGroup map[int]int = map[int]int{}
var IdxEntry_IdxToName map[int]string = map[int]string{}
var IdxEntry_NameToIdx map[string]int = map[string]int{}

var DUMMP_IdxEntryFalse bool = base.SetNameIsStrunct("IdxEntry", base.ToBool("False"))

func SetIdxEntryFields(nName, fName, fType string, fNum int) bool {

	base.RequestSettingNameFields(nName, fName, fType, fNum)

	enumFtype, ok := base.NameToType[fType]
	if ok {
		IdxEntrySetIdxToType(fNum, enumFtype)
	}
	//FIXME: basic type only store?

	IdxEntrySetIdxToName(fNum, fType)

	grp := IdxEntryGetTypeGroup(fType)
	IdxEntrySetTypeGroup(fNum, grp)

	IdxEntry_IdxToName[fNum] = fType

	IdxEntry_NameToIdx[fName] = fNum
	base.SetNameToIdx("IdxEntry", IdxEntry_NameToIdx)

	return true

}
func IdxEntrySetIdxToName(i int, s string) {
	IdxEntry_IdxToName[i] = s

	base.SetIdxToName("IdxEntry", IdxEntry_IdxToName)
}

func IdxEntrySetIdxToType(k, v int) bool {
	IdxEntry_IdxToType[k] = v
	base.SetIdxToType("IdxEntry", IdxEntry_IdxToType)
	return true
}

func IdxEntrySetTypeGroup(k, v int) bool {
	IdxEntry_IdxToTypeGroup[k] = v
	base.SetdxToTypeGroup("IdxEntry", IdxEntry_IdxToTypeGroup)
	return true
}

func IdxEntryGetTypeGroup(s string) (result int) {
	return base.GetTypeGroup(s)
}

func (node IdxEntry) commonNode() *base.CommonNode {
	if node.CommonNode == nil {
		log.Log(log.LOG_WARN, func() log.LogArgs {
			return log.F("CommonNode not found IdxEntry")
		})
	} else if len(node.CommonNode.Name) == 0 || len(node.CommonNode.IdxToType) == 0 {
		node.CommonNode.Name = "IdxEntry"
		node.CommonNode.IdxToType = IdxEntry_IdxToType
		node.CommonNode.IdxToTypeGroup = IdxEntry_IdxToTypeGroup
	}
	return node.CommonNode
}
func (node IdxEntry) SearchInfo(pos int, fn base.RecFn, condFn base.CondFn) {

	node.commonNode().SearchInfo(pos, fn, condFn)

}

func (node IdxEntry) Info() (info base.Info) {

	return node.commonNode().Info()

}

func (node IdxEntry) IsLeafAt(j int) bool {

	return node.commonNode().IsLeafAt(j)

}

func (node IdxEntry) CountOfField() int {
	return len(IdxEntry_IdxToType)
}

func (node IdxEntry) ValueInfo(i int) base.ValueInfo {
	return node.commonNode().ValueInfo(i)
}

func (node IdxEntry) FieldAt(idx int) *base.CommonNode {
	return node.commonNode().FieldAt(idx)
}

type IdxEntryWithErr struct {
	*IdxEntry
	Err error
}

func IdxEntrySingle(node *IdxEntry, e error) IdxEntryWithErr {
	return IdxEntryWithErr{IdxEntry: node, Err: e}
}

func NewIdxEntry() *IdxEntry {
	base.ApplyRequestNameFields()
	node := emptyIdxEntry()
	node.NodeList = &base.NodeList{}
	node.CommonNode.Name = "IdxEntry"
	node.Init()

	return node
}

func (node IdxEntry) FieldGroups() map[int]int {
	return IdxEntry_IdxToTypeGroup
}

func (node IdxEntry) Root() (Root, error) {
	if !node.InRoot() {
		return Root{}, log.ERR_NO_INCLUDE_ROOT
	}
	root := toRoot(node.Base)
	return root, nil
}
