// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	IndexNum_Indexes_0 int = base.AtoiNoErr(Atoi("0"))
	IndexNum_Indexes   int = IndexNum_Indexes_0
)

// (field inedx, field type) -> IndexNum_IdxToType
var DUMMY_IndexNum_Indexes bool = SetIndexNumFields("IndexNum", "Indexes", "[]KeyRecord", IndexNum_Indexes_0)

func (node IndexNum) Indexes() (result *KeyRecordList) {
	result = emptyKeyRecordList()
	common := node.FieldAt(IndexNum_Indexes_0)
	if common.Node == nil {
		result = NewKeyRecordList()
		node.SetFieldAt(IndexNum_Indexes_0, result.SelfAsCommonNode())
		common = node.FieldAt(IndexNum_Indexes_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

//func (node IndexNum) SetIndexes(v *base.CommonNode) error {
func (node IndexNum) SetIndexes(v *KeyRecordList) error {

	return node.CommonNode.SetFieldAt(0, v.SelfAsCommonNode())
}
