// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	InvertedMapNum_Key_0 int = base.AtoiNoErr(Atoi("0"))
	InvertedMapNum_Key   int = InvertedMapNum_Key_0
)

// (field inedx, field type) -> InvertedMapNum_IdxToType
var DUMMY_InvertedMapNum_Key bool = SetInvertedMapNumFields("InvertedMapNum", "Key", "Int64", InvertedMapNum_Key_0)

func (node InvertedMapNum) Key() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(InvertedMapNum_Key_0)
	if common.Node == nil {
		result = NewCommonNode()
		node.SetFieldAt(InvertedMapNum_Key_0, result.SelfAsCommonNode())
		common = node.FieldAt(InvertedMapNum_Key_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

//func (node InvertedMapNum) SetKey(v *base.CommonNode) error {
func (node InvertedMapNum) SetKey(v *CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v.SelfAsCommonNode())
}
