// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	InvertedMapNum_Value_1 int = base.AtoiNoErr(Atoi("1"))
	InvertedMapNum_Value   int = InvertedMapNum_Value_1
)

// (field inedx, field type) -> InvertedMapNum_IdxToType
var DUMMY_InvertedMapNum_Value bool = SetInvertedMapNumFields("InvertedMapNum", "Value", "Record", InvertedMapNum_Value_1)

func (node InvertedMapNum) Value() (result *Record) {
	result = emptyRecord()
	common := node.FieldAt(InvertedMapNum_Value_1)
	if common.Node == nil {
		result = NewRecord()
		node.SetFieldAt(InvertedMapNum_Value_1, result.SelfAsCommonNode())
		common = node.FieldAt(InvertedMapNum_Value_1)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

//func (node InvertedMapNum) SetValue(v *base.CommonNode) error {
func (node InvertedMapNum) SetValue(v *Record) error {

	return node.CommonNode.SetFieldAt(1, v.SelfAsCommonNode())
}
