// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type InvertedMapNumList struct { // genny
	*CommonNode
}

// InvertedMapNum genny
func NewInvertedMapNumList() *InvertedMapNumList {

	list := emptyInvertedMapNumList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]InvertedMapNum"

	list.InitList()
	return list
}

func emptyInvertedMapNumList() *InvertedMapNumList {
	return &InvertedMapNumList{CommonNode: &base.CommonNode{}}
}

func (node InvertedMapNumList) At(i int) (result *InvertedMapNum, e error) {
	result = &InvertedMapNum{}
	result.CommonNode, e = node.CommonNode.At(i)
	return
}

func (node InvertedMapNumList) SetAt(i int, v *InvertedMapNum) error {
	return node.CommonNode.SetAt(i, v.CommonNode)
}

func (node InvertedMapNumList) First() (result *InvertedMapNum, e error) {
	return node.At(0)
}

func (node InvertedMapNumList) Last() (result *InvertedMapNum, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node InvertedMapNumList) Select(fn func(*InvertedMapNum) bool) (result []*InvertedMapNum) {
	result = make([]*InvertedMapNum, 0, int(node.NodeList.ValueInfo.VLen))
	commons := node.CommonNode.Select(func(cm *CommonNode) bool {
		return fn(&InvertedMapNum{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &InvertedMapNum{CommonNode: cm})
	}
	return result
}

func (node InvertedMapNumList) Find(fn func(*InvertedMapNum) bool) *InvertedMapNum {
	result := &InvertedMapNum{}
	result.CommonNode = node.CommonNode.Find(func(cm *CommonNode) bool {
		return fn(&InvertedMapNum{CommonNode: cm})
	})
	return result
}

func (node InvertedMapNumList) All() []*InvertedMapNum {
	return node.Select(func(*InvertedMapNum) bool { return true })
}

func (node InvertedMapNumList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}
