// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type KeyRecordList struct { // genny
	*CommonNode
}

// KeyRecord genny
func NewKeyRecordList() *KeyRecordList {

	list := emptyKeyRecordList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]KeyRecord"

	(*base.List)(list.CommonNode).InitList()
	return list
}

func emptyKeyRecordList() *KeyRecordList {
	return &KeyRecordList{CommonNode: &base.CommonNode{}}
}

func (node KeyRecordList) At(i int) (result *KeyRecord, e error) {
	result = &KeyRecord{}
	result.CommonNode, e = (*base.List)(node.CommonNode).At(i)
	return
}

func (node KeyRecordList) AtWihoutError(i int) (result *KeyRecord) {
	result, e := node.At(i)
	if e != nil {
		result = nil
	}
	return
}

func (node KeyRecordList) SetAt(i int, v *KeyRecord) error {
	return (*base.List)(node.CommonNode).SetAt(i, v.CommonNode)
}
func (node KeyRecordList) Add(v KeyRecordList) error {
	return (*base.List)(node.CommonNode).Add((*base.List)(v.CommonNode))
}

func (node KeyRecordList) Range(start, last int) *KeyRecordList {
	l := (*base.List)(node.CommonNode).New(base.OptRange(start, last))
	if l == nil {
		return nil
	}
	return &KeyRecordList{CommonNode: (*base.CommonNode)(l)}
}

func (node KeyRecordList) First() (result *KeyRecord, e error) {
	return node.At(0)
}

func (node KeyRecordList) Last() (result *KeyRecord, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node KeyRecordList) Select(fn func(*KeyRecord) bool) (result []*KeyRecord) {
	result = make([]*KeyRecord, 0, int(node.NodeList.ValueInfo.VLen))
	commons := (*base.List)(node.CommonNode).Select(func(cm *CommonNode) bool {
		return fn(&KeyRecord{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &KeyRecord{CommonNode: cm})
	}
	return result
}

func (node KeyRecordList) Find(fn func(*KeyRecord) bool) *KeyRecord {
	result := &KeyRecord{}
	result.CommonNode = (*base.List)(node.CommonNode).Find(func(cm *CommonNode) bool {
		return fn(&KeyRecord{CommonNode: cm})
	})
	return result
}

func (node KeyRecordList) All() []*KeyRecord {
	return node.Select(func(*KeyRecord) bool { return true })
}

func (node KeyRecordList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}

func (node KeyRecordList) SwapAt(i, j int) error {
	return (*List)(node.CommonNode).SwapAt(i, j)
}

func (node KeyRecordList) SortBy(less func(i, j int) bool) error {
	return (*List)(node.CommonNode).SortBy(less)
}

// Search ... binary search
func (node KeyRecordList) Search(fn func(*KeyRecord) bool) *KeyRecord {
	result := &KeyRecord{}

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&KeyRecord{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		result, _ = node.At(i)
	}

	return result
}

func (node KeyRecordList) SearchIndex(fn func(*KeyRecord) bool) int {

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&KeyRecord{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		return i
	}

	return -1
}
