// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"github.com/kazu/fbshelper/query/base"
	"github.com/kazu/fbshelper/query/log"
)

/*
must call 1 times per Table / struct ( KeyRecord ) ;
*/

type KeyRecord struct {
	*base.CommonNode
}

func emptyKeyRecord() *KeyRecord {
	return &KeyRecord{CommonNode: &base.CommonNode{}}
}

var KeyRecord_IdxToType map[int]int = map[int]int{}
var KeyRecord_IdxToTypeGroup map[int]int = map[int]int{}
var KeyRecord_IdxToName map[int]string = map[int]string{}
var KeyRecord_NameToIdx map[string]int = map[string]int{}

var DUMMP_KeyRecordFalse bool = base.SetNameIsStrunct("KeyRecord", base.ToBool("False"))

func SetKeyRecordFields(nName, fName, fType string, fNum int) bool {

	base.RequestSettingNameFields(nName, fName, fType, fNum)

	enumFtype, ok := base.NameToType[fType]
	if ok {
		KeyRecordSetIdxToType(fNum, enumFtype)
	}
	//FIXME: basic type only store?

	KeyRecordSetIdxToName(fNum, fType)

	grp := KeyRecordGetTypeGroup(fType)
	KeyRecordSetTypeGroup(fNum, grp)

	KeyRecord_IdxToName[fNum] = fType

	KeyRecord_NameToIdx[fName] = fNum
	base.SetNameToIdx("KeyRecord", KeyRecord_NameToIdx)

	return true

}
func KeyRecordSetIdxToName(i int, s string) {
	KeyRecord_IdxToName[i] = s

	base.SetIdxToName("KeyRecord", KeyRecord_IdxToName)
}

func KeyRecordSetIdxToType(k, v int) bool {
	KeyRecord_IdxToType[k] = v
	base.SetIdxToType("KeyRecord", KeyRecord_IdxToType)
	return true
}

func KeyRecordSetTypeGroup(k, v int) bool {
	KeyRecord_IdxToTypeGroup[k] = v
	base.SetdxToTypeGroup("KeyRecord", KeyRecord_IdxToTypeGroup)
	return true
}

func KeyRecordGetTypeGroup(s string) (result int) {
	return base.GetTypeGroup(s)
}

func (node KeyRecord) commonNode() *base.CommonNode {
	if node.CommonNode == nil {
		log.Log(log.LOG_WARN, func() log.LogArgs {
			return log.F("CommonNode not found KeyRecord")
		})
	} else if len(node.CommonNode.Name) == 0 || len(node.CommonNode.IdxToType) == 0 {
		node.CommonNode.Name = "KeyRecord"
		node.CommonNode.IdxToType = KeyRecord_IdxToType
		node.CommonNode.IdxToTypeGroup = KeyRecord_IdxToTypeGroup
	}
	return node.CommonNode
}
func (node KeyRecord) SearchInfo(pos int, fn base.RecFn, condFn base.CondFn) {

	node.commonNode().SearchInfo(pos, fn, condFn)

}

func (node KeyRecord) Info() (info base.Info) {

	return node.commonNode().Info()

}

func (node KeyRecord) IsLeafAt(j int) bool {

	return node.commonNode().IsLeafAt(j)

}

func (node KeyRecord) CountOfField() int {
	return len(KeyRecord_IdxToType)
}

func (node KeyRecord) ValueInfo(i int) base.ValueInfo {
	return node.commonNode().ValueInfo(i)
}

func (node KeyRecord) FieldAt(idx int) *base.CommonNode {
	return node.commonNode().FieldAt(idx)
}

func (src KeyRecord) Equal(dst KeyRecord) bool {
	for i := 0; i < src.CountOfField(); i++ {
		if !src.FieldAt(i).Equal(dst.FieldAt(i)) {
			return false
		}
	}
	return true
}

type KeyRecordWithErr struct {
	*KeyRecord
	Err error
}

func KeyRecordSingle(node *KeyRecord, e error) KeyRecordWithErr {
	return KeyRecordWithErr{KeyRecord: node, Err: e}
}

func NewKeyRecord() *KeyRecord {
	base.ApplyRequestNameFields()
	node := emptyKeyRecord()
	node.NodeList = &base.NodeList{}
	node.CommonNode.Name = "KeyRecord"
	node.Init()

	return node
}

func (node KeyRecord) FieldGroups() map[int]int {
	return KeyRecord_IdxToTypeGroup
}

func (node KeyRecord) Root() (Root, error) {
	if !node.InRoot() {
		return Root{}, log.ERR_NO_INCLUDE_ROOT
	}
	root := toRoot(node.Base)
	return root, nil
}
