// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	KeyRecord_Key_0 int = base.AtoiNoErr(Atoi("0"))
	KeyRecord_Key   int = KeyRecord_Key_0
)

// (field inedx, field type) -> KeyRecord_IdxToType
var DUMMY_KeyRecord_Key bool = SetKeyRecordFields("KeyRecord", "Key", "Uint64", KeyRecord_Key_0)

func (node KeyRecord) Key() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(KeyRecord_Key_0)
	if common.Node == nil {
		result = NewCommonNode()
		node.SetFieldAt(KeyRecord_Key_0, result.SelfAsCommonNode())
		common = node.FieldAt(KeyRecord_Key_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

//func (node KeyRecord) SetKey(v *base.CommonNode) error {
func (node KeyRecord) SetKey(v *CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v.SelfAsCommonNode())
}
