// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	KeyRecord_Records_1 int = base.AtoiNoErr(Atoi("1"))
	KeyRecord_Records   int = KeyRecord_Records_1
)

// (field inedx, field type) -> KeyRecord_IdxToType
var DUMMY_KeyRecord_Records bool = SetKeyRecordFields("KeyRecord", "Records", "[]Record", KeyRecord_Records_1)

func (node KeyRecord) Records() (result *RecordList) {
	result = emptyRecordList()
	common := node.FieldAt(KeyRecord_Records_1)
	if common.Node == nil {
		result = NewRecordList()
		node.SetFieldAt(KeyRecord_Records_1, result.SelfAsCommonNode())
		common = node.FieldAt(KeyRecord_Records_1)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node KeyRecord) SetRecords(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(1, v)
}
