// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	PathInfo_Path_0 int = base.AtoiNoErr(Atoi("0"))
	PathInfo_Path   int = PathInfo_Path_0
)

// (field inedx, field type) -> PathInfo_IdxToType
var DUMMY_PathInfo_Path bool = SetPathInfoFields("PathInfo", "Path", "[]byte", PathInfo_Path_0)

func (node PathInfo) Path() (result *List) {
	result = emptyList()
	common := node.FieldAt(PathInfo_Path_0)
	if common.Node == nil {
		result = NewList()
		node.SetFieldAt(PathInfo_Path_0, result.SelfAsCommonNode())
		common = node.FieldAt(PathInfo_Path_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

//func (node PathInfo) SetPath(v *base.CommonNode) error {
func (node PathInfo) SetPath(v *List) error {

	return node.CommonNode.SetFieldAt(0, v.SelfAsCommonNode())
}
