// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type PathInfoList struct { // genny
	*CommonNode
}

// PathInfo genny
func NewPathInfoList() *PathInfoList {

	list := emptyPathInfoList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]PathInfo"

	(*base.List)(list.CommonNode).InitList()
	return list
}

func emptyPathInfoList() *PathInfoList {
	return &PathInfoList{CommonNode: &base.CommonNode{}}
}

func (node PathInfoList) At(i int) (result *PathInfo, e error) {
	result = &PathInfo{}
	result.CommonNode, e = (*base.List)(node.CommonNode).At(i)
	return
}

func (node PathInfoList) SetAt(i int, v *PathInfo) error {
	return (*base.List)(node.CommonNode).SetAt(i, v.CommonNode)
}

func (node PathInfoList) First() (result *PathInfo, e error) {
	return node.At(0)
}

func (node PathInfoList) Last() (result *PathInfo, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node PathInfoList) Select(fn func(*PathInfo) bool) (result []*PathInfo) {
	result = make([]*PathInfo, 0, int(node.NodeList.ValueInfo.VLen))
	commons := (*base.List)(node.CommonNode).Select(func(cm *CommonNode) bool {
		return fn(&PathInfo{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &PathInfo{CommonNode: cm})
	}
	return result
}

func (node PathInfoList) Find(fn func(*PathInfo) bool) *PathInfo {
	result := &PathInfo{}
	result.CommonNode = (*base.List)(node.CommonNode).Find(func(cm *CommonNode) bool {
		return fn(&PathInfo{CommonNode: cm})
	})
	return result
}

func (node PathInfoList) All() []*PathInfo {
	return node.Select(func(*PathInfo) bool { return true })
}

func (node PathInfoList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}

func (node PathInfoList) SwapAt(i, j int) error {
	return (*List)(node.CommonNode).SwapAt(i, j)
}

func (node PathInfoList) SortBy(less func(i, j int) bool) error {
	return (*List)(node.CommonNode).SortBy(less)
}

// Search ... binary search
func (node PathInfoList) Search(fn func(*PathInfo) bool) *PathInfo {
	result := &PathInfo{}

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&PathInfo{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		result, _ = node.At(i)
	}

	return result
}

func (node PathInfoList) SearchIndex(fn func(*PathInfo) bool) int {

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&PathInfo{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		return i
	}

	return -1
}
