// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Record_Size_2 int = base.AtoiNoErr(Atoi("2"))
	Record_Size   int = Record_Size_2
)

// (field inedx, field type) -> Record_IdxToType
var DUMMY_Record_Size bool = SetRecordFields("Record", "Size", "Int64", Record_Size_2)

func (node Record) Size() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(Record_Size_2)
	if common.Node == nil {
		result = NewCommonNode()
		node.SetFieldAt(Record_Size_2, result.SelfAsCommonNode())
		common = node.FieldAt(Record_Size_2)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

//func (node Record) SetSize(v *base.CommonNode) error {
func (node Record) SetSize(v *CommonNode) error {

	return node.CommonNode.SetFieldAt(2, v.SelfAsCommonNode())
}
