// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Record_Offset_1 int = base.AtoiNoErr(Atoi("1"))
	Record_Offset   int = Record_Offset_1
)

// (field inedx, field type) -> Record_IdxToType
var DUMMY_Record_Offset bool = SetRecordFields("Record", "Offset", "Int64", Record_Offset_1)

func (node Record) Offset() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(Record_Offset_1)
	if common.Node == nil {
		result = NewCommonNode()
		node.SetFieldAt(Record_Offset_1, result.SelfAsCommonNode())
		common = node.FieldAt(Record_Offset_1)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

//func (node Record) SetOffset(v *base.CommonNode) error {
func (node Record) SetOffset(v *CommonNode) error {

	return node.CommonNode.SetFieldAt(1, v.SelfAsCommonNode())
}
