// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Record_FileId_0 int = base.AtoiNoErr(Atoi("0"))
	Record_FileId   int = Record_FileId_0
)

// (field inedx, field type) -> Record_IdxToType
var DUMMY_Record_FileId bool = SetRecordFields("Record", "FileId", "Uint64", Record_FileId_0)

func (node Record) FileId() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(Record_FileId_0)
	if common.Node == nil {
		result = NewCommonNode()
		node.SetFieldAt(Record_FileId_0, result.SelfAsCommonNode())
		common = node.FieldAt(Record_FileId_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node Record) SetFileId(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v)
}
