// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Root_IndexType_1 int = base.AtoiNoErr(Atoi("1"))
	Root_IndexType   int = Root_IndexType_1
)

// (field inedx, field type) -> Root_IdxToType
var DUMMY_Root_IndexType bool = SetRootFields("Root", "IndexType", "Byte", Root_IndexType_1)

func (node Root) IndexType() (result *CommonNode) {
	result = emptyCommonNode()
	common := node.FieldAt(Root_IndexType_1)
	if common.Node == nil {
		result = NewCommonNode()
		node.SetFieldAt(Root_IndexType_1, result.SelfAsCommonNode())
		common = node.FieldAt(Root_IndexType_1)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

//func (node Root) SetIndexType(v *base.CommonNode) error {
func (node Root) SetIndexType(v *CommonNode) error {

	return node.CommonNode.SetFieldAt(1, v.SelfAsCommonNode())
}
