// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Root_Index_2 int = base.AtoiNoErr(Atoi("2"))
	Root_Index   int = Root_Index_2
)

// (field inedx, field type) -> Root_IdxToType
var DUMMY_Root_Index bool = SetRootFields("Root", "Index", "Index", Root_Index_2)

func (node Root) Index() (result *Index) {
	result = emptyIndex()
	common := node.FieldAt(Root_Index_2)
	if common.Node == nil {
		result = NewIndex()
		node.SetFieldAt(Root_Index_2, result.SelfAsCommonNode())
		common = node.FieldAt(Root_Index_2)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node Root) SetIndex(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(2, v)
}
