// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type RootList struct { // genny
	*CommonNode
}

// Root genny
func NewRootList() *RootList {

	list := emptyRootList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]Root"

	(*base.List)(list.CommonNode).InitList()
	return list
}

func emptyRootList() *RootList {
	return &RootList{CommonNode: &base.CommonNode{}}
}

func (node RootList) At(i int) (result *Root, e error) {
	result = &Root{}
	result.CommonNode, e = (*base.List)(node.CommonNode).At(i)
	return
}

func (node RootList) SetAt(i int, v *Root) error {
	return (*base.List)(node.CommonNode).SetAt(i, v.CommonNode)
}

func (node RootList) First() (result *Root, e error) {
	return node.At(0)
}

func (node RootList) Last() (result *Root, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node RootList) Select(fn func(*Root) bool) (result []*Root) {
	result = make([]*Root, 0, int(node.NodeList.ValueInfo.VLen))
	commons := (*base.List)(node.CommonNode).Select(func(cm *CommonNode) bool {
		return fn(&Root{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &Root{CommonNode: cm})
	}
	return result
}

func (node RootList) Find(fn func(*Root) bool) *Root {
	result := &Root{}
	result.CommonNode = (*base.List)(node.CommonNode).Find(func(cm *CommonNode) bool {
		return fn(&Root{CommonNode: cm})
	})
	return result
}

func (node RootList) All() []*Root {
	return node.Select(func(*Root) bool { return true })
}

func (node RootList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}

func (node RootList) SwapAt(i, j int) error {
	return (*List)(node.CommonNode).SwapAt(i, j)
}

func (node RootList) SortBy(less func(i, j int) bool) error {
	return (*List)(node.CommonNode).SortBy(less)
}

// Search ... binary search
func (node RootList) Search(fn func(*Root) bool) *Root {
	result := &Root{}

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&Root{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		result, _ = node.At(i)
	}

	return result
}
