// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

type SymbolList struct { // genny
	*CommonNode
}

// Symbol genny
func NewSymbolList() *SymbolList {

	list := emptySymbolList()
	list.NodeList = &base.NodeList{}
	list.CommonNode.Name = "[]Symbol"

	(*base.List)(list.CommonNode).InitList()
	return list
}

func emptySymbolList() *SymbolList {
	return &SymbolList{CommonNode: &base.CommonNode{}}
}

func (node SymbolList) At(i int) (result *Symbol, e error) {
	result = &Symbol{}
	result.CommonNode, e = (*base.List)(node.CommonNode).At(i)
	return
}

func (node SymbolList) SetAt(i int, v *Symbol) error {
	return (*base.List)(node.CommonNode).SetAt(i, v.CommonNode)
}

func (node SymbolList) First() (result *Symbol, e error) {
	return node.At(0)
}

func (node SymbolList) Last() (result *Symbol, e error) {
	return node.At(int(node.NodeList.ValueInfo.VLen) - 1)
}

func (node SymbolList) Select(fn func(*Symbol) bool) (result []*Symbol) {
	result = make([]*Symbol, 0, int(node.NodeList.ValueInfo.VLen))
	commons := (*base.List)(node.CommonNode).Select(func(cm *CommonNode) bool {
		return fn(&Symbol{CommonNode: cm})
	})
	for _, cm := range commons {
		result = append(result, &Symbol{CommonNode: cm})
	}
	return result
}

func (node SymbolList) Find(fn func(*Symbol) bool) *Symbol {
	result := &Symbol{}
	result.CommonNode = (*base.List)(node.CommonNode).Find(func(cm *CommonNode) bool {
		return fn(&Symbol{CommonNode: cm})
	})
	return result
}

func (node SymbolList) All() []*Symbol {
	return node.Select(func(*Symbol) bool { return true })
}

func (node SymbolList) Count() int {
	return int(node.NodeList.ValueInfo.VLen)
}

func (node SymbolList) SwapAt(i, j int) error {
	return (*List)(node.CommonNode).SwapAt(i, j)
}

func (node SymbolList) SortBy(less func(i, j int) bool) error {
	return (*List)(node.CommonNode).SortBy(less)
}

// Search ... binary search
func (node SymbolList) Search(fn func(*Symbol) bool) *Symbol {
	result := &Symbol{}

	i := (*base.List)(node.CommonNode).SearchIndex(int((*base.List)(node.CommonNode).VLen()), func(cm *CommonNode) bool {
		return fn(&Symbol{CommonNode: cm})
	})
	if i < int((*base.List)(node.CommonNode).VLen()) {
		result, _ = node.At(i)
	}

	return result
}
