// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/kazu/fbshelper/query/base"

/*
genny must be called per Field
*/

var (
	Symbols_Symbols_0 int = base.AtoiNoErr(Atoi("0"))
	Symbols_Symbols   int = Symbols_Symbols_0
)

// (field inedx, field type) -> Symbols_IdxToType
var DUMMY_Symbols_Symbols bool = SetSymbolsFields("Symbols", "Symbols", "[]Symbol", Symbols_Symbols_0)

func (node Symbols) Symbols() (result *SymbolList) {
	result = emptySymbolList()
	common := node.FieldAt(Symbols_Symbols_0)
	if common.Node == nil {
		result = NewSymbolList()
		node.SetFieldAt(Symbols_Symbols_0, result.SelfAsCommonNode())
		common = node.FieldAt(Symbols_Symbols_0)
	}

	result.Name = common.Name
	result.NodeList = common.NodeList
	result.IdxToType = common.IdxToType
	result.IdxToTypeGroup = common.IdxToTypeGroup

	return
}

func (node Symbols) SetSymbols(v *base.CommonNode) error {

	return node.CommonNode.SetFieldAt(0, v)
}
